from __future__ import annotations

from dataclasses import dataclass

import numpy as np
from numpy.typing import NDArray

from policyreclab.simulation.environment import SyntheticBanditEnvironment

FloatArray = NDArray[np.float64]
IntArray = NDArray[np.int64]


@dataclass(frozen=True)
class LoggedBanditData:
    """Observed one-step interactions generated by a behavior policy."""

    context_indices: IntArray
    actions: IntArray
    rewards: IntArray
    behavior_propensities: FloatArray

    @property
    def n_rounds(self) -> int:
        return int(self.rewards.size)

    @property
    def mean_reward(self) -> float:
        return float(np.mean(self.rewards))


def _validate_behavior_probabilities(
    probabilities: FloatArray,
    *,
    n_contexts: int,
    n_actions: int,
) -> FloatArray:
    probabilities = np.asarray(probabilities, dtype=np.float64)
    if probabilities.shape != (n_contexts, n_actions):
        raise ValueError(
            "behavior probabilities must have shape "
            f"({n_contexts}, {n_actions}), got {probabilities.shape}"
        )
    if not np.all(np.isfinite(probabilities)):
        raise ValueError("behavior probabilities must be finite")
    if np.any(probabilities < 0.0):
        raise ValueError("behavior probabilities must be non-negative")
    if not np.allclose(probabilities.sum(axis=1), 1.0, atol=1e-12):
        raise ValueError("each context's behavior probabilities must sum to 1")
    return probabilities


def simulate_logged_bandit_data(
    environment: SyntheticBanditEnvironment,
    behavior_probabilities: FloatArray,
    *,
    n_rounds: int,
    seed: int = 0,
) -> LoggedBanditData:
    """Generate logged interactions under a fixed behavior policy.

    Contexts are sampled uniformly with replacement from the finite context
    population. Only the chosen action's reward is observed.
    """
    if n_rounds <= 0:
        raise ValueError("n_rounds must be positive")

    probabilities = _validate_behavior_probabilities(
        behavior_probabilities,
        n_contexts=environment.n_users,
        n_actions=environment.n_items,
    )
    rng = np.random.default_rng(seed)
    contexts = rng.integers(0, environment.n_users, size=n_rounds, dtype=np.int64)
    actions = np.empty(n_rounds, dtype=np.int64)
    rewards = np.empty(n_rounds, dtype=np.int64)
    propensities = np.empty(n_rounds, dtype=np.float64)

    for i, context_index in enumerate(contexts):
        row = probabilities[int(context_index)]
        action = int(rng.choice(environment.n_items, p=row))
        actions[i] = action
        propensities[i] = row[action]
        rewards[i] = environment.sample_reward(
            user_index=int(context_index),
            item_index=action,
            rng=rng,
        )

    return LoggedBanditData(
        context_indices=contexts,
        actions=actions,
        rewards=rewards,
        behavior_propensities=propensities,
    )
